# General settings for the pipeline
general:
  cpiApiServiceKeyCredentialsId: "desgauthapikey"

# Define the pipeline stages
stages:
  # We use a custom name to avoid the template's default 'Build' logic
  Preparation:
    steps:
      - name: "Get iFlow Artifact from Git"
        integrationArtifactUpload:
          packageId: "dev_tenant_cicd"
          filePath: "calling_iflows_from_other_cpi_account.zip"

  # The Deploy stage
  Deploy:
    steps:
      - name: "Deploy iFlow and Update Address"
        cloudIntegrationDeploy:
          integrationFlowId: "calling_iflows_from_other_cpi_account_Created"
          configurationFile: "prod_config.json"
