# General settings for the pipeline
general:
  # The credential for your DEV tenant
  cpiApiServiceKeyCredentialsId: "desgauthapikey"

# Define the pipeline stages
stages:
  # This stage gets your iFlow from Git
  Build:
    steps:
      - name: "Get iFlow from Git"
        integrationArtifactUpload:
          packageId: "dev_tenant_cicd"
          # Use the filename with no spaces
          filePath: "calling_iflows_from_other_cpi_account.zip"

  # This stage DEPLOYS (UPDATES) your iFlow in the DEV tenant
  Deploy:
    steps:
      - name: "Deploy to Dev and Update Address"
        cloudIntegrationDeploy:
          # This tells the pipeline to use the JSON file to update the URL
          configurationFile: "prod_config.json"
          # NO destination is needed because we are deploying to the home tenant.